from color import Color

# ============ Test color presets generated by ai ============ #
COLORS = {
    # ------------- Misc ------------- #
    'white': Color(0, 0, 100),
    'black': Color(0, 0, 0),
    'gray': Color(0, 0, 50),
    'background': Color(220, 15, 25),     # Dark bluish-gray background

    # ------------ Text ------------ #
    'text_primary': Color(0, 0, 95),      # White text
    'text_secondary': Color(220, 5, 75),  # Light gray text
    'text_error': Color(5, 80, 85),       # Reddish alert text

    # ----------- Buttons ----------- #
    'btn_primary': Color(210, 50, 75),    # Main action button (blue)
    'btn_success': Color(120, 50, 70),    # Success/confirm (green)
    'btn_warning': Color(35, 90, 90),     # Warn (orange)
    'btn_error': Color(0, 75, 85),        # Destructive (red)
    'btn_neutral': Color(210, 5, 55),     # For subtle/inactive buttons

    'btn_ca': Color(275, 40, 85),         # Purple tag for Certificate Authority
    'btn_aa': Color(30, 90, 85),          # Orange tag for Attribute Authority
    'btn_user': Color(150, 40, 85),       # Teal/green tag for Users
}
